### ISSUE TITLE
Add font-awesome icons to buttons

### ISSUE THREAD

**Issue by ashryanbeats** [CreativeSDK/web-image-editor-drag-and-drop#14]

**Comment by ashryanbeats** [comment]
Remove the word "Image" from all

**Comment by Dubsta** [comment]
I'd like to give this a shot.

**Comment by Dubsta** [comment]
Why not glyphicons? The project already has bootstrap 3 and they are built in. Is there a reason to use font-awesome over glyphicons?

**Comment by ashryanbeats** [comment]
Glyphicons are also welcome!
